### ISSUE TITLE
There is no method for parsing a network.Address.IPv6

### ISSUE THREAD

**Issue by lbirkert** [ikskuh/zig-network#54]
IPv4 has a parsing method, why is there none for IPv6?

**Comment by MasterQ32** [comment]
Because nobody seems to have needed that yet. Feel free to implement it if you need it!

**Comment by KekOnTheWorld** [comment]
I ended up using .getEndPointList, this would still be good for consistency accross the lib tho. (Especially cuz IPv6 is constantly gaining availability and new users)

**Comment by Saiv46** [comment]
`std.net` includes `parseIp6(buf: []const u8, port: u16) IPv6ParseError!Address`
